import {
  User,
  Eye,
  Pencil,
  Trash2,
  Download,
} from "lucide-react";

const CertificateTable = ({ certificates }) => {
  return (
    <div className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">

      <div className="overflow-x-auto">

        <table className="w-full">

          <thead className="bg-slate-50">

            <tr className="text-left text-sm font-semibold text-slate-600">

              <th className="px-5 py-3">Student</th>

              <th className="px-5 py-3">Program</th>

              <th className="px-5 py-3">Certificate ID</th>

              <th className="px-5 py-3">Issued On</th>

              <th className="px-5 py-3">Generated By</th>

              <th className="px-5 py-3">Status</th>

              <th className="px-5 py-3 text-center">
                Certificate
              </th>

              <th className="px-5 py-3 text-center">
                Action
              </th>

            </tr>

          </thead>

          <tbody>

            {certificates.map((item) => (

              <tr
                key={item.id}
                className="border-t border-slate-100 transition hover:bg-slate-50"
              >

                {/* Student */}

                <td className="px-5 py-4">

                  <div className="flex items-center gap-3">

                    <div className="flex h-11 w-11 items-center justify-center rounded-xl bg-sky-100">

                      <User
                        size={20}
                        className="text-sky-600"
                      />

                    </div>

                    <div>

                      <h3 className="text-[15px] font-semibold text-slate-800">
                        {item.name}
                      </h3>

                      <p className="text-xs text-slate-500">
                        {item.email}
                      </p>

                    </div>

                  </div>

                </td>

                {/* Program */}

                <td className="px-5 py-4">

                  <span className="rounded-full bg-sky-100 px-3 py-1 text-xs font-medium text-sky-700">
                    {item.program}
                  </span>

                </td>

                {/* Certificate ID */}

                <td className="px-5 py-4">

                  <span className="text-sm font-medium text-slate-700">
                    {item.certificateId}
                  </span>

                </td>

                {/* Date */}

                <td className="px-5 py-4">

                  <span className="text-sm text-slate-600">
                    {item.issueDate}
                  </span>

                </td>

                {/* Generated By */}

                <td className="px-5 py-4">

                  <span className="rounded-full bg-violet-100 px-3 py-1 text-xs font-medium text-violet-700">
                    {item.method}
                  </span>

                </td>

                {/* Status */}

                <td className="px-5 py-4">

                  <span
                    className={`rounded-full px-3 py-1 text-xs font-medium ${
                      item.status === "Issued"
                        ? "bg-green-100 text-green-700"
                        : "bg-yellow-100 text-yellow-700"
                    }`}
                  >
                    {item.status}
                  </span>

                </td>

                {/* View Certificate */}

                <td className="px-5 py-4">

                  <div className="flex justify-center">

                    <button className="flex items-center gap-2 rounded-lg bg-indigo-50 px-3 py-2 text-xs font-medium text-indigo-600 transition hover:bg-indigo-100">

                      <Download size={15} />

                      View

                    </button>

                  </div>

                </td>

                {/* Action */}

                <td className="px-5 py-4">

                  <div className="flex justify-center gap-2">

                    <button className="flex h-9 w-9 items-center justify-center rounded-lg bg-sky-50 text-sky-600 transition hover:bg-sky-100">

                      <Eye size={16} />

                    </button>

                    <button className="flex h-9 w-9 items-center justify-center rounded-lg bg-green-50 text-green-600 transition hover:bg-green-100">

                      <Pencil size={16} />

                    </button>

                    <button className="flex h-9 w-9 items-center justify-center rounded-lg bg-red-50 text-red-600 transition hover:bg-red-100">

                      <Trash2 size={16} />

                    </button>

                  </div>

                </td>

              </tr>

            ))}

          </tbody>

        </table>

      </div>

    </div>
  );
};

export default CertificateTable;